// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class NoteContentResult {
  final bool ok;
  final String errorMessage;
  final String content;

  const NoteContentResult({
    required this.ok,
    required this.errorMessage,
    required this.content,
  });

  @override
  int get hashCode => ok.hashCode ^ errorMessage.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteContentResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          errorMessage == other.errorMessage &&
          content == other.content;
}

class NoteIndexEntry {
  final String path;
  final String name;
  final String title;
  final String preview;
  final String kind;
  final PlatformInt64 modifiedMillis;
  final PlatformInt64 sizeBytes;

  const NoteIndexEntry({
    required this.path,
    required this.name,
    required this.title,
    required this.preview,
    required this.kind,
    required this.modifiedMillis,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      title.hashCode ^
      preview.hashCode ^
      kind.hashCode ^
      modifiedMillis.hashCode ^
      sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteIndexEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          title == other.title &&
          preview == other.preview &&
          kind == other.kind &&
          modifiedMillis == other.modifiedMillis &&
          sizeBytes == other.sizeBytes;
}

class NoteIndexListResult {
  final bool ok;
  final String errorMessage;
  final List<NoteIndexEntry> notes;

  const NoteIndexListResult({
    required this.ok,
    required this.errorMessage,
    required this.notes,
  });

  @override
  int get hashCode => ok.hashCode ^ errorMessage.hashCode ^ notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteIndexListResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          errorMessage == other.errorMessage &&
          notes == other.notes;
}

class NoteIndexRefreshResult {
  final bool ok;
  final String errorMessage;
  final int indexedCount;
  final int removedCount;

  const NoteIndexRefreshResult({
    required this.ok,
    required this.errorMessage,
    required this.indexedCount,
    required this.removedCount,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      errorMessage.hashCode ^
      indexedCount.hashCode ^
      removedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteIndexRefreshResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          errorMessage == other.errorMessage &&
          indexedCount == other.indexedCount &&
          removedCount == other.removedCount;
}

class NoteSearchFileResult {
  final NoteIndexEntry note;
  final List<NoteSearchLineMatch> matches;

  const NoteSearchFileResult({required this.note, required this.matches});

  @override
  int get hashCode => note.hashCode ^ matches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteSearchFileResult &&
          runtimeType == other.runtimeType &&
          note == other.note &&
          matches == other.matches;
}

class NoteSearchLineMatch {
  final int lineNumber;
  final String lineText;
  final int matchStartUtf16;
  final int matchEndUtf16;

  const NoteSearchLineMatch({
    required this.lineNumber,
    required this.lineText,
    required this.matchStartUtf16,
    required this.matchEndUtf16,
  });

  @override
  int get hashCode =>
      lineNumber.hashCode ^
      lineText.hashCode ^
      matchStartUtf16.hashCode ^
      matchEndUtf16.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteSearchLineMatch &&
          runtimeType == other.runtimeType &&
          lineNumber == other.lineNumber &&
          lineText == other.lineText &&
          matchStartUtf16 == other.matchStartUtf16 &&
          matchEndUtf16 == other.matchEndUtf16;
}

class NoteSearchResult {
  final bool ok;
  final String errorMessage;
  final List<NoteSearchFileResult> files;

  const NoteSearchResult({
    required this.ok,
    required this.errorMessage,
    required this.files,
  });

  @override
  int get hashCode => ok.hashCode ^ errorMessage.hashCode ^ files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteSearchResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          errorMessage == other.errorMessage &&
          files == other.files;
}
